export default [
    'women Ethnic',
    'women Ethnic sarees',
    'women Ethnic Silk sarees',
    'women Ethnic banarasi Silk sarees',
    'women Ethnic Cotton Sarees',
    'women Ethnic Georgette Sarees',
    'women Ethnic Chiffon Sarees',
    'women Ethnic Heavy Work Sarees',
    'women Ethnic net Sarees',
    'women Ethnic kurtis',
    'women Ethnic Anarkali Kurtis',
    'women Ethnic Rayon Kurtis',
    'women Ethnic Cotton Kurtis',
    'women Ethnic Chikankari Kurtis',
    'women Ethnic kurta sets',
    'women Ethnic Kurta Palazzo Sets',
    'women Ethnic Rayon Kurta Sets',
    'women Ethnic Kurta Pant Sets',
    'women Ethnic Cotton Kurta Sets',
    'women Ethnic Sharara Sets',
    'women Ethnic Dupatta Sets',
    'women Ethnic Cotton Sets',
    'women Ethnic Rayon Sets',
    'women Ethnic Printed Sets',
    'women Ethnic Suits & Dress Material',
    'women Ethnic Cotton Suits',
    'women Ethnic Embroidered Suits',
    'women Ethnic Crepe Suits',
    'women Ethnic Silk Suits',
    'women Ethnic Patiala Suits',
    'women Ethnic Lehengas',
    'women Ethnic Lehenga Cholis',
    'women Ethnic Net Lehenga',
    'women Ethnic Bridal Lehenga',
    'women Ethnic Other Ethnic',
    'women Ethnic Blouses',
    'women Ethnic Dupattas',
    'women Ethnic Lehanga',
    'women Ethnic Gown',
    'women Ethnic Skirts & Bottomwear',
    'women Ethnic Islamic Fashion',
    'women Ethnic Petticoats',
    'Women Western',
    'Women Western Topwear',
    'Women Western Tops',
    'Women Western Dresses',
    'Women Western T-shirts',
    'Women Western Jumpsuits',
    'Women Western Bottomwear',
    'Women Western Jeans & Jeggings',
    'Women Western Trousers & Pants',
    'Women Western Palazzos',
    'Women Western Shorts',
    'Women Western Skirts',
    'Women Western Innerwear',
    'Women Western Bra',
    'Women Western Women Innerwear',
    'Women Western Briefs',
    'Women Western Sleepwear',
    'Women Western Nightsuits',
    'Women Western Women Nightdress',
    'Women Western Maternity Wear',
    'Women Western All Maternity & Feedingwear',
    'Women Western Maternity Kurtis & Dresses',
    'Women Western Sports Wear',
    'Women Western All Women Sportwear',
    'Women Western Sports Bra',
    'Men',
    'Men Top Wear',
    'Men Tshirts',
    'Men Shirts',
    'Men Winter Wear',
    'Men Jackets',
    'Men Sweater and Sweatshirts',
    'Men Bottom Wear',
    'Men Track Pants',
    'Men Jeans',
    'Men Trousers',
    'Men Shorts',
    'Men Dhotis',
    'Men Men Accessories',
    'Men Watches',
    'Men Belts & Wallets',
    'Men Jewellery',
    'Men Sunglasses',
    'Men Bags',
    'Men Men Footwear',
    'Men Casual Shoes',
    'Men Sports Shoes',
    'Men Flip Flops & Sandals',
    'Men Formal Shoes',
    'Men Loafers',
    'Men Ethnic Wear',
    'Men Kurtas Sets',
    'Men Ethnic Jackets',
    'Men Bottomwear',
    'Men Inner & Sleep Wear',
    'Men Boxers',
    'Men Tops',
    'Kids',
    'Kids Boys & Girls 2+ Years',
    'Kids Dresses',
    'Kids Boys Sets',
    'Kids Girls Sets',
    'Kids Ethnicwear',
    'Kids Nightwear',
    'Kids Winter Wear',
    'Kids Top Wear',
    'Kids Bottomwear',
    'Kids Infant 0-2 Years',
    'Kids Rompers',
    'Kids Baby Sets',
    'Kids Ethnicwear',
    'Kids Toys & Accessories',
    'Kids Soft Toys',
    'Kids Footwear',
    'Kids Stationery',
    'Kids Watches',
    'Kids Bags & Backpacks',
    'Kids Baby Care',
    'Kids Baby Bedding & Accessories',
    'Kids All Baby Care',
    'Kids Newborn Care',
    'Home & Kitchen',
    'Home & Kitchen Kitchen & Appliances',
    'Home & Kitchen Kitchen Tools',
    'Home & Kitchen Storage & Organizers',
    'Home & Kitchen Appliances',
    'Home & Kitchen Cookware',
    'Home & Kitchen Dinnerware',
    'Home & Kitchen Bakeware',
    'Home & Kitchen Glasses & Barware',
    'Home & Kitchen Home Furnishing',
    'Home & Kitchen Bedsheets',
    'Home & Kitchen Curtains & Sheers',
    'Home & Kitchen Pillows',
    'Home & Kitchen Cushions & Cushion Covers',
    'Home & Kitchen Carpets & Doormats',
    'Home & Kitchen Mattress Protectors',
    'Home & Kitchen Sofa & Diwan Sets',
    'Home & Kitchen Towels & Bathrobes',
    'Home & Kitchen Blankets',
    'Home & Kitchen Home Decor',
    'Home & Kitchen Appliances Covers',
    'Home & Kitchen Clocks',
    'Home & Kitchen Storage & Organizers',
    'Home & Kitchen Showpieces',
    'Home & Kitchen Paintings & Photoframes',
    'Home & Kitchen Stickers & Wallpapers',
    'Home & Kitchen Lights',
    'Home & Kitchen Gifts & Mugs',
    'Home & Kitchen Kitchen & Dining',
    'Home & Kitchen Kitchen Storage',
    'Home & Kitchen Cookware & Bakeware',
    'Home & Kitchen Home Improvement',
    'Home & Kitchen Cleaning Supplies',
    'Home & Kitchen Gardening',
    'Home & Kitchen Bathroom Accessories',
    'Home & Kitchen Insect Protection',
    'Home & Kitchen Home Tools',
    'Beauty & Health',
    'Beauty & Health Make up',
    'Beauty & Health Face',
    'Beauty & Health Eyes',
    'Beauty & Health Lips',
    'Beauty & Health Nails',
    'Beauty & Health Make up Kits',
    'Beauty & Health Appliances',
    'Beauty & Health Brushes & Tools',
    'Beauty & Health Makeup Accessories',
    'Beauty & Health Skincare',
    'Beauty & Health Face Masks & Peels',
    'Beauty & Health Facecare',
    'Beauty & Health Haircare',
    'Beauty & Health Bath & Shower',
    'Beauty & Health Baby & Mom',
    'Beauty & Health Baby Personal Care',
    'Beauty & Health Mom Care',
    'Beauty & Health Mens Care',
    'Beauty & Health Beard Care',
    'Beauty & Health Fragrances for Men',
    'Beauty & Health Healthcare',
    'Beauty & Health Ear Buds & Cleaners',
    'Beauty & Health Condoms',
    'Beauty & Health Sanitary Pads',
    'Beauty & Health Dental Care',
    'Beauty & Health Weight Management',
    'Beauty & Health Health Monitors',
    'Jewellery & Accessories',
    'Jewellery & Accessories Jewellery',
    'Jewellery & Accessories Jewellery Set',
    'Jewellery & Accessories Earrings & Studs',
    'Jewellery & Accessories Mangalsutras',
    'Jewellery & Accessories Tops',
    'Jewellery & Accessories Necklaces',
    'Jewellery & Accessories Tops',
    'Jewellery & Accessories Kamarbandh & Maangtika',
    'Jewellery & Accessories Anklets',
    'Jewellery & Accessories Men Jewellery',
    'Jewellery & Accessories Oxidised',
    'Jewellery & Accessories Men Accessories',
    'Jewellery & Accessories Men Watches',
    'Jewellery & Accessories Men Sunglasses',
    'Jewellery & Accessories Belts & Wallets',
    'Jewellery & Accessories Men Tops',
    'Jewellery & Accessories Women Accessory',
    'Jewellery & Accessories Women Watches',
    'Jewellery & Accessories Hair Accessories',
    'Jewellery & Accessories Women Sunglasses',
    'Jewellery & Accessories Women Tops',
    'Jewellery & Accessories Scarves and Stoles',
    'Bags & Footwear',
    'Bags & Footwear Women Bags',
    'Bags & Footwear Handbags',
    'Bags & Footwear Clutches',
    'Bags & Footwear Slingbags',
    'Bags & Footwear Wallets',
    'Bags & Footwear Backpacks',
    'Bags & Footwear Men Bags',
    'Bags & Footwear Men Wallets',
    'Bags & Footwear Crossbody Bags & Sling Bags',
    'Bags & Footwear Waist Bags',
    'Bags & Footwear Travel Bags',
    'Bags & Footwear Duffel & Trolley Bags',
    'Bags & Footwear Men Footwear',
    'Bags & Footwear Sports Shoes',
    'Bags & Footwear Casual Shoes',
    'Bags & Footwear Formal Shoes',
    'Bags & Footwear Sandals',
    'Bags & Footwear Loafers',
    'Bags & Footwear Women Footwear',
    'Bags & Footwear Flats',
    'Bags & Footwear Bellies',
    'Bags & Footwear Heals and Sandals',
    'Bags & Footwear Boots',
    'Bags & Footwear Flipflops & Slippers',
    'Bags & Footwear Kids Footwear',
    'Bags & Footwear Boys Shoes',
    'Bags & Footwear Girls Shoes',
    'Bags & Footwear Casual Shoes',
    'Bags & Footwear Flipflops & Slippers',
    'Bags & Footwear Sandals',
    'Electronics',
    'Electronics Audio',
    'Electronics Bluetooth Headphone & Earphones',
    'Electronics Wired Headphones & Earphones',
    'Electronics Speakers',
    'Electronics Mobile & Accessories',
    'Electronics Smart watches',
    'Electronics Mobile Holders',
    'Electronics Power Bank',
    'Electronics Mobile cases and covers',
    'Electronics Mobile Chargers',
    'Electronics Smart Wearables',
    'Electronics VR Box',
    'Electronics Tripod',
    'Electronics Microphone',
    'Electronics Photo & Video Accessories',
    'Sports & Fitness',
    'Sports & Fitness Fitness',
    'Sports & Fitness Yoga',
    'Sports & Fitness Hand Grip Strengthener',
    'Sports & Fitness Abs Wheel Roller',
    'Sports & Fitness Skipping Ropes',
    'Sports & Fitness Sweat Belts',
    'Sports & Fitness Sports',
    'Sports & Fitness Bandminton',
    'Sports & Fitness Skating',
    'Sports & Fitness Football',
    'Sports & Fitness Cricket',
    'Car & Motorbike',
    'Car & Motorbike Car Accessories',
    'Car & Motorbike Car Covers',
    'Car & Motorbike Interior Accessories',
    'Car & Motorbike Car Mobile Holders',
    'Car & Motorbike Car Repair Assistance',
    'Car & Motorbike Moterbike Accessories',
    'Car & Motorbike Helmets',
    'Car & Motorbike Bike Accessories',
    'Car & Motorbike Bike LED Lights',
    'Car & Motorbike Safety Gear & Clothing',
    'Office Supplies & Stationery',
    'Office Supplies & Stationery Office Supplies & Stationery',
    'Office Supplies & Stationery Diaries & Notebooks',
    'Office Supplies & Stationery Adhesives & Tapes',
    'Office Supplies & Stationery Files & Desks Organizers',
    'Office Supplies & Stationery Pens & Pencils',
    'Office Supplies & Stationery Paintings & Photoframes',
    'Pet Supplies',
    'Pet Supplies Pet Toys',
    'Pet Supplies Pet Grooming',
    'Pet Supplies Pet Food',
    'Pet Supplies Pet Clothing',
    'Pet Supplies Pet Health',
    'Food & Drinks',
    'Food & Drinks Dry Fruits',
    'Food & Drinks Tea',
    'Food & Drinks Masalas',
    'Food & Drinks Coffee',
    'Food & Drinks Ready to Cook',
    'Musical Instruments',
    'Musical Instruments String Instruments',
    'Musical Instruments Musical Accessories',
    'Musical Instruments Wind Instruments',
    'Books',
    'Books Fiction & Non Fiction',
    'Books Childrens Books',
    'Books Self Help Books',
    'Books Novels',
    'Books Economics & Commerce',
    'Books Religious Books',
    'Books Academic Books',
    'Books School Textbooks & Guides',
    'Books Reference Books',
]
